const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Behaviors.Pin,
		C3.Plugins.Browser,
		C3.Plugins.Facebook,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Facebook.Acts.LogIn2,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.SetVolume
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{BG: 0},
	{Solid: 0},
	{Block: 0},
	{Platform: 0},
	{Sine: 0},
	{Player: 0},
	{Touch: 0},
	{Keyboard: 0},
	{DistanceDisplay: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{coin: 0},
	{DistanceDisplay2: 0},
	{gifft_score: 0},
	{gift2: 0},
	{coin_particle: 0},
	{run_score2: 0},
	{newgame: 0},
	{facebook: 0},
	{more_game: 0},
	{restart: 0},
	{Santatxt: 0},
	{over: 0},
	{Audio: 0},
	{Fade: 0},
	{wave_txt: 0},
	{sound_mute: 0},
	{Pin: 0},
	{Santa: 0},
	{Sprite5: 0},
	{play_tuto: 0},
	{treebg: 0},
	{Bird: 0},
	{Pengu: 0},
	{Snowball: 0},
	{tree2: 0},
	{stone: 0},
	{snow1: 0},
	{snow2: 0},
	{BestScoreFont: 0},
	{gui: 0},
	{menu_button: 0},
	{Browser: 0},
	{tree1: 0},
	{Sprite10: 0},
	{Particles: 0},
	{Facebook2: 0},
	{twitter_button: 0},
	{Particles2: 0},
	{Sprite: 0},
	{fade: 0},
	{TiledBackground: 0},
	{Seal: 0},
	{Pengu_Slide: 0},
	{Particles3: 0},
	{iglo: 0},
	{Sprite2: 0},
	{destroyer: 0},
	{SpriteFont: 0},
	{enemy: 0},
	{button: 0},
	{Best: 0},
	{dead: 0},
	{power: 0},
	{gift: 0},
	{stage: 0},
	{TotalDistance: 0},
	{CurrentDistance: 0},
	{NextBlock: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Block: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	DistanceDisplay: class extends self.ITextInstance {},
	coin: class extends self.ISpriteInstance {},
	DistanceDisplay2: class extends self.ITextInstance {},
	gifft_score: class extends self.ISpriteFontInstance {},
	gift2: class extends self.ISpriteInstance {},
	coin_particle: class extends self.IParticlesInstance {},
	run_score2: class extends self.ISpriteFontInstance {},
	newgame: class extends self.ISpriteInstance {},
	facebook: class extends self.ISpriteInstance {},
	more_game: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Santatxt: class extends self.ISpriteInstance {},
	over: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	wave_txt: class extends self.ISpriteInstance {},
	sound_mute: class extends self.ISpriteInstance {},
	Santa: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	play_tuto: class extends self.ISpriteInstance {},
	treebg: class extends self.ITiledBackgroundInstance {},
	Bird: class extends self.ISpriteInstance {},
	Pengu: class extends self.ISpriteInstance {},
	Snowball: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	stone: class extends self.ISpriteInstance {},
	snow1: class extends self.ISpriteInstance {},
	snow2: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	gui: class extends self.ISpriteInstance {},
	menu_button: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	tree1: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Facebook2: class extends self.IInstance {},
	twitter_button: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Seal: class extends self.ISpriteInstance {},
	Pengu_Slide: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	iglo: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	destroyer: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	enemy: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {}
}